# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_example

  target 'ios_exampleUITests' do
    # Pods for testing
  end
pod "AFNetworking"
end

target 'TwoTarget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwoTarget
end
